export const CHARACTERS = [
  {
    id: 'cowboy',
    name: 'KOVBOY',
    file: 'Cowboy_Male.glb',
    price: 0,
    emoji: '🤠',
    desc: 'Varsayılan jokey',
    color: '#c8881b',
  },
  {
    id: 'casual',
    name: 'KASUAL',
    file: 'Casual_Male.glb',
    price: 200,
    emoji: '👤',
    desc: 'Sıradan bir binici',
    color: '#4a90d9',
  },
  {
    id: 'ninja',
    name: 'NİNJA',
    file: 'Ninja_Male.glb',
    price: 500,
    emoji: '🥷',
    desc: 'Gizem ustası',
    color: '#222',
  },
  {
    id: 'viking',
    name: 'VİKİNG',
    file: 'Viking_Male.glb',
    price: 800,
    emoji: '⚔️',
    desc: 'Kuzeyden gelen savaşçı',
    color: '#7a5530',
  },
  {
    id: 'pirate',
    name: 'KORSAN',
    file: 'Pirate_Male.glb',
    price: 1000,
    emoji: '🏴‍☠️',
    desc: 'Denizlerin efendisi',
    color: '#1a1a4a',
  },
  {
    id: 'zombie',
    name: 'ZOMBİ',
    file: 'Zombie_Male.glb',
    price: 1200,
    emoji: '🧟',
    desc: 'Ölümsüz jokey',
    color: '#3a5c1a',
  },
  {
    id: 'knight',
    name: 'ALTIN ŞOVALYE',
    file: 'Knight_Golden_Male.glb',
    price: 2000,
    emoji: '👑',
    desc: 'Efsanevi savaşçı',
    color: '#c8a000',
  },
  {
    id: 'wizard',
    name: 'BÜYÜCÜ',
    file: 'Wizard.glb',
    price: 2500,
    emoji: '🧙',
    desc: 'Gizemli güçler',
    color: '#6a0080',
  },
];
