export const HORSES = [
  {
    id: 'chestnut',
    name: 'ANADOLU ALASI',
    price: 0,
    bodyColor: '#8d6e63',
    maneColor: '#5d4037',
    hoofColor: '#3e2723',
    desc: 'Sağlam ve güvenilir',
    accentColor: '#8d6e63',
    baseSpeedMult: 1.0,
    baseManeuvMult: 1.0,
    baseJumpMult: 1.0,
    baseMaxSpeed: 40,
  },
  {
    id: 'black',
    name: 'KARAYEL',
    price: 250,
    bodyColor: '#212121',
    maneColor: '#111111',
    hoofColor: '#0a0a0a',
    desc: 'Siyah Fırtına',
    accentColor: '#424242',
    baseSpeedMult: 1.4,
    baseManeuvMult: 0.9,
    baseJumpMult: 1.1,
    baseMaxSpeed: 60,
  },
  {
    id: 'white',
    name: 'AKKOR KÜHEYLAN',
    price: 600,
    bodyColor: '#EDE8D8',
    maneColor: '#C0B898',
    hoofColor: '#8a8070',
    desc: 'Parlak ve efsanevi',
    accentColor: '#ffecb3',
    baseSpeedMult: 1.8,
    baseManeuvMult: 1.3,
    baseJumpMult: 1.5,
    baseMaxSpeed: 80,
  },
  {
    id: 'pamuk',
    name: 'PAMUK',
    price: 1200,
    bodyColor: '#fdfdfb',
    maneColor: '#e6e6ea',
    hoofColor: '#9a9aa2',
    desc: 'Bembeyaz, narin ve hızlı',
    accentColor: '#ffffff',
    baseSpeedMult: 1.6,
    baseManeuvMult: 1.5,
    baseJumpMult: 1.3,
    baseMaxSpeed: 75,
    // Farklı, statik low-poly model (CC0 Quaternius) — prosedürel koşu animasyonu
    model: '/assets/models/pamuk_horse.glb',
    animated: false,
    modelScale: 0.85,
    modelY: -0.05,
    previewY: 0.2,
  },
];

export const MAX_UPGRADE_LEVEL = 5;
export const upgradeCost = (currentLevel) => (currentLevel + 1) * 75;
