export const HORSES = [
  {
    id: 'chestnut',
    name: 'ANADOLU ALASI',
    price: 0,
    bodyColor: '#8d6e63',
    maneColor: '#5d4037',
    hoofColor: '#3e2723',
    desc: 'Sağlam ve güvenilir',
    accentColor: '#8d6e63',
    baseSpeedMult: 1.2,
    baseManeuvMult: 1.1,
    baseJumpMult: 1.1,
    baseMaxSpeed: 50,
  },
  {
    id: 'black',
    name: 'KARAYEL',
    price: 250,
    bodyColor: '#212121',
    maneColor: '#111111',
    hoofColor: '#0a0a0a',
    desc: 'Siyah Fırtına',
    accentColor: '#424242',
    baseSpeedMult: 1.4,
    baseManeuvMult: 0.9,
    baseJumpMult: 1.1,
    baseMaxSpeed: 60,
  },
  {
    id: 'white',
    name: 'AKKOR KÜHEYLAN',
    price: 600,
    bodyColor: '#EDE8D8',
    maneColor: '#C0B898',
    hoofColor: '#8a8070',
    desc: 'Parlak ve efsanevi',
    accentColor: '#ffecb3',
    baseSpeedMult: 1.8,
    baseManeuvMult: 1.3,
    baseJumpMult: 1.5,
    baseMaxSpeed: 80,
  },
  {
    id: 'stylized_chestnut',
    name: 'KESTANE',
    price: 0,
    bodyColor: '#8a5a2b',
    maneColor: '#5a3a18',
    hoofColor: '#2a1a0a',
    desc: 'Stilize kestane at (gerçek koşu animasyonlu)',
    accentColor: '#c8843c',
    baseSpeedMult: 1.3,
    baseManeuvMult: 1.2,
    baseJumpMult: 1.2,
    baseMaxSpeed: 58,
    // Özel iskeletli model (.blend → GLB), kendi "run" animasyonu var
    model: '/assets/models/horses/chestnut_stylized.glb',
    modelScale: 0.6,
    modelY: -1.0,
    animClip: 'run',
    skeletal: true,
    noTint: true,
  },
  {
    id: 'pamuk',
    name: 'PAMUK',
    price: 1200,
    bodyColor: '#ffffff',
    maneColor: '#f2f2f5',
    hoofColor: '#d8d8de',
    whiteWash: true, // dokuyu temizleyip bembeyaz yap
    desc: 'Bembeyaz, narin ve hızlı',
    accentColor: '#ffffff',
    baseSpeedMult: 1.6,
    baseManeuvMult: 1.5,
    baseJumpMult: 1.3,
    baseMaxSpeed: 75,
  },
];

export const MAX_UPGRADE_LEVEL = 5;
export const upgradeCost = (currentLevel) => 750 * Math.pow(2, currentLevel);
